### ISSUE TITLE
关于数据预处理

### ISSUE THREAD

**Issue by MingYangi** [nju-websoft/GLRE#4]
您好，数据处理时，发现了报错，是缺少文件，我看了在data_processing/tools.py给出的路径中GLRE-master\data_processing\common\geniass的确是缺少了一个文件，可是文件里是什么呢？
错误如下：
Traceback (most recent call last):
  File "process.py", line 118, in <module>
    main()
  File "process.py", line 57, in main
    split_sents = sentence_split_genia(orig_sentences)
  File "/mnt/d/code/GLRE-master/data_processing/tools.py", line 244, in sentence_split_genia
    with open('temp_file.split.txt', 'r') as ifile:
FileNotFoundError: [Errno 2] No such file or directory: 'temp_file.split.txt'

非常期待您的回复！

**Comment by slzbywdf** [comment]
你好，common\geniass下面是安装的GENIA工具。具体下载的方式在README.md中有写。

**Comment by MingYangi** [comment]
emmm，我有点没太明白你的意思，我的意思是说，我按照步骤进行的处理，然否执行到sh process_cdr.sh时 出现了上面的错误，缺少文件的错误，就是接下来我应该怎么办呢？还是我之前处理的有问题呢？

**Comment by slzbywdf** [comment]
可能是你没有正确安装genia。我在Ubuntu18.04上新测试了一遍是可以正确跑通的。

**Comment by SeaYM** [comment]
Traceback (most recent call last):
  File "process.py", line 12, in <module>
    from tools import sentence_split_genia, tokenize_genia
  File "/mnt/d/code/GLRE-master/data_processing/tools.py", line 21, in <module>
    genia_tagger = GENIATagger(os.path.join("./common", "genia-tagger-py", "geniatagger-3.0.2", "**_geniatagger_**"))
  File "./common/genia-tagger-py/geniatagger.py", line 29, in __init__
    self.process = subprocess.Popen(
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './**_geniatagger_**'


这个geniatagger文件在哪里，放的是什么呢？我有重新下载了你这个包，然后遇到了这个问题

**Comment by MingYangi** [comment]
我有重新下载了包，下载之后并有一些temp_file包，后来发现这一系列的包是生成的，有生成temp_file、temp_file.txt.result,但是就是没有生成temp_file.split.txt文件。我也是不知道怎么回事儿了，那您刚刚重新跑的代码是在这里下载的么？

**Comment by slzbywdf** [comment]
我是在这个github的代码上重新跑的。 你是否有安装genia-tagger的python包装器，即执行以下4步吗
 1. git clone https://github.com/bornabesic/genia-tagger-py.git
 2. cd genia-tagger-py 
 3. Here, you should modify the Makefile inside genia-tagger-py and replace line 3 with `wget http://www.nactem.ac.uk/GENIA/tagger/geniatagger-3.0.2.tar.gz`
 4.  make

**Comment by MingYangi** [comment]
对呀对呀，这次make之后才出现那两个temp_file文件，但是就是没有我说的缺的那个，就是不知道怎么回事儿

**Comment by slzbywdf** [comment]
你是否有修改makefile文件内容（第三步需要修改下载地址）。没有*. split. txt应该就是geniass不能运行(●°u°●)​ 」

**Comment by MingYangi** [comment]
嘻嘻嘻嘻嘻嘻嘻  我也修改了  哈哈哈哈哈哈   就是复制你给的那段替换D:\code\GLRE-master\data_processing\common\genia-tagger-py中的Makefile的第三行wget的内容，我哭了要，不过很是谢谢你哈

**Comment by MingYangi** [comment]
如果您方便，可以加一下您的方便的联系方式吗？之后可能还会有一些小问题向您请教

**Comment by pangkunli** [comment]
你好，我在运行scripts/run_cdr.py时，修改了指定GPU，从默认的0改成了2，但之后运行的时候出现的错误说我使用了GPU0，我们服务器GPU0已经满了，因此我把文件中parser.add_argument('--gpu', type=str, default='2')，从0改成了2,。但是报错我使用的GPU0，config文件中我把extra的gpu也改成了2，请问还有哪里需要修改的吗

**Comment by 314556185** [comment]
> 您好，数据处理时，发现了报错，是缺少文件，我看了在data_processing/tools.py给出的路径中GLRE-master\data_processing\common\geniass的确是缺少了一个文件，可是文件里是什么呢？
> 错误如下：
> Traceback (most recent call last):
> File "process.py", line 118, in
> main()
> File "process.py", line 57, in main
> split_sents = sentence_split_genia(orig_sentences)
> File "/mnt/d/code/GLRE-master/data_processing/tools.py", line 244, in sentence_split_genia
> with open('temp_file.split.txt', 'r') as ifile:
> FileNotFoundError: [Errno 2] No such file or directory: 'temp_file.split.txt'
> 
> 非常期待您的回复！

请问您的问题解决了吗？我也遇到了一模一样的问题。希望您看到可以联系我一下，17700583334

**Comment by 314556185** [comment]
> 我有重新下载了包，下载之后并有一些temp_file包，后来发现这一系列的包是生成的，有生成temp_file、temp_file.txt.result,但是就是没有生成temp_file.split.txt文件。我也是不知道怎么回事儿了，那您刚刚重新跑的代码是在这里下载的么？

安装一下ruby,All you have to do is run sudo apt-get install ruby-full

**Comment by li-muz** [comment]
> 

请问你解决这个问题了吗 ， 我也碰到了

**Comment by li-muz** [comment]
> 
解决了，是服务器没有安装ruby导致geniass安装失败

**Comment by shiqqaingzhu** [comment]
Traceback (most recent call last):
  File "process.py", line 118, in <module>
    main()
  File "process.py", line 37, in main
    abstracts, entities, relations = readPubTator(args)
  File "/ai/zsq/GLRE/data_processing/readers.py", line 27, in readPubTator
    with open(args.input_file, 'r') as infile:
FileNotFoundError: [Errno 2] No such file or directory: '../data/CDR/CDR.Corpus.v010516/CDR_TestSet.PubTator.txt'  请问，执行sh process_cdr.sh 该脚本·命令后出现了上面的错误如何解决啊？
